name: ProMART
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  enable_coderay: true
  coderay:
    coderay_line_numbers: true
    coderay_css: class
highlighter: rouge
baseurl:
url: http://promart.io
plugins:
  - jekyll-sitemap

exclude:
  - CNAME
  - README.md

defaults:
  -
    scope:
      path: apps
      type: blogs
    values:
      layout: product
      category: apps
  -
    scope:
      path: components
      type: blogs
    values:
      layout: component
      category: components
 